//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReunionesBack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estados_reunion_usuario
    {
        public int id_usuario { get; set; }
        public int id_estado_reunion { get; set; }
        public int id_reunion { get; set; }
        public int vigencia { get; set; }
    
        public virtual Estados_reunion Estados_reunion { get; set; }
        public virtual Reunion Reunion { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
