//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReunionesBack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reunion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reunion()
        {
            this.Estados_reunion_usuario = new HashSet<Estados_reunion_usuario>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public int owner { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estados_reunion_usuario> Estados_reunion_usuario { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
